### ISSUE TITLE
Tooltip breaks vulkanize

### ISSUE THREAD

**Issue by ergo** [PolymerElements/paper-tooltip#83]
### Description
After i add paper-tooltip to fresh project template generated by `polymer init`.

The build command fails, this doesn't happen with other paper* components, it would also be worth metioning would be that using polymer serve the tooltip element works fine

### Steps to reproduce

1. Start a blank application template with `polymer init`
2. Add this import `<link rel="import" href="../../bower_components/paper-tooltip/paper-tooltip.html">`
3. Run build 

### Expected outcome
Build command should pass

### Actual outcome

> ergo@ergo-virtual-machine:~/workspace/rhodecode-app$ polymer build
> info:    Building application...
> info:    Generating build/unbundled...
> info:    Generating build/bundled...
> error:   Promise rejection: Error: file path is not in root: /bower_components/web-animations-js/web-animations-next-lite.min.js (/home/ergo/workspace/rhodecode-app)
> error:   Error: file path is not in root: /bower_components/web-animations-js/web-animations-next-lite.min.js (/home/ergo/workspace/rhodecode-app)
>     at Object.urlFromPath (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/path-transformers.js:41:15)
>     at StreamAnalyzer.getFile (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:107:39)
>     at StreamResolver.accept (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:210:34)
>     at FileLoader.request (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:64:27)
>     at Object.<anonymous> (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/vulcanize/lib/vulcan.js:318:26)
>     at Array.map (native)
>     at Object.inlineScripts (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/vulcanize/lib/vulcan.js:311:34)
>     at Object.<anonymous> (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/vulcanize/lib/vulcan.js:458:21)
>     at run (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
>     at /home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
> error:   Promise rejection: Error: file path is not in root: /bower_components/web-animations-js/web-animations-next-lite.min.js (/home/ergo/workspace/rhodecode-app)
> error:   Error: file path is not in root: /bower_components/web-animations-js/web-animations-next-lite.min.js (/home/ergo/workspace/rhodecode-app)
>     at Object.urlFromPath (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/path-transformers.js:41:15)
>     at StreamAnalyzer.getFile (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:107:39)
>     at StreamResolver.accept (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:210:34)
>     at FileLoader.request (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/lib/loader/file-loader.js:64:27)
>     at Object.<anonymous> (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/vulcanize/lib/vulcan.js:318:26)
>     at Array.map (native)
>     at Object.inlineScripts (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/vulcanize/lib/vulcan.js:311:34)
>     at Object.<anonymous> (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/vulcanize/lib/vulcan.js:458:21)
>     at run (/home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
>     at /home/ergo/BinProgs/node/lib/node_modules/polymer-cli/node_modules/polymer-build/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28

**Comment by ergo** [comment]
Sorry, can be closed, it really appears to be issue with `polymer-cli`.

npm install -g polymer-cli@0.13.0 - build passes
npm install -g polymer-cli@0.14.0 - build breaks

I got this bug also on `iron-ajax` element (some elements build just fine in 0.14.0)
